from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, is_dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from insightron.services.transcription.contracts import (
    DiarizationResult,
    LowConfidenceWord,
    TranscriptionMetrics,
)


class MarkdownRenderer:
    def render_dashboard(
        self,
        *,
        audio_path: str,
        segments: List[Dict[str, Any]],
        metrics: Optional[TranscriptionMetrics],
        diarization: Optional[DiarizationResult],
        engine_model: str,
        backend: str,
        formatting_style: str,
        processed_at: Optional[str] = None,
    ) -> str:
        processed_at = processed_at or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        file_hash = self._file_hash(audio_path)

        full_text = " ".join((seg.get("text") or "").strip() for seg in segments).strip()

        md_lines: List[str] = []
        md_lines.append("---")
        md_lines.append("# Insightron Transcription Report")
        md_lines.append("")
        md_lines.append(f"**Source File:** `{audio_path}`")
        md_lines.append(f"**Processed On:** {processed_at}")
        md_lines.append(f"**File Hash (SHA256):** `{file_hash}`")
        md_lines.append(f"**Engine:** Whisper `{engine_model}` · {backend}")
        md_lines.append(f"**Formatting:** `{formatting_style}`")
        md_lines.append("---")
        md_lines.append("")

        md_lines.append("## Transcription Quality Dashboard")
        md_lines.append("")
        if metrics is None:
            md_lines.append("_Metrics unavailable._")
        else:
            md_lines.extend(self._render_metrics_table(metrics))
        md_lines.append("")

        if diarization is not None and diarization.turns:
            md_lines.append("## Speaker Timeline")
            md_lines.append("")
            md_lines.append(self._render_speaker_timeline(diarization))
            md_lines.append("")

        md_lines.append("## Full Transcript")
        md_lines.append("")
        md_lines.append(full_text or "_No transcript text._")
        md_lines.append("")

        md_lines.append("## Timestamped Segments")
        md_lines.append("")
        md_lines.append(self._render_segments(segments))
        md_lines.append("")

        md_lines.append("## Low-Confidence Flags")
        md_lines.append("")
        if metrics is None:
            md_lines.append("_Metrics unavailable._")
        else:
            md_lines.append(self._render_low_confidence(metrics.low_confidence_words))
        md_lines.append("")

        md_lines.append("## Raw Metadata")
        md_lines.append("")
        raw = {
            "engine_model": engine_model,
            "backend": backend,
            "formatting_style": formatting_style,
            "processed_at": processed_at,
            "metrics": self._to_jsonable(metrics),
            "diarization": self._to_jsonable(diarization),
        }
        md_lines.append("```json")
        md_lines.append(json.dumps(raw, ensure_ascii=False, indent=2))
        md_lines.append("```")
        md_lines.append("")
        md_lines.append("---")
        md_lines.append("*Generated by Insightron · Single-Phase Engine*")
        md_lines.append("")
        return "\n".join(md_lines)

    def _render_metrics_table(self, m: TranscriptionMetrics) -> List[str]:
        def pct(x: float) -> str:
            return f"{x*100:.1f}%"

        def status(val: float, good: float, warn: float) -> str:
            if val >= good:
                return "Excellent"
            if val >= warn:
                return "Fair"
            return "Poor"

        def flag(val: float, good: float, warn: float) -> str:
            if val <= good:
                return "Low"
            if val <= warn:
                return "Moderate"
            return "High"

        lines = [
            "| Metric | Value | Status |",
            "|---|---:|---|",
            f"| Avg. Confidence | {pct(m.avg_confidence)} | {status(m.avg_confidence, 0.90, 0.75)} |",
            f"| Min. Confidence | {pct(m.min_confidence)} | {status(m.min_confidence, 0.75, 0.50)} |",
            f"| Low-Confidence Ratio | {pct(m.low_confidence_ratio)} | {flag(m.low_confidence_ratio, 0.10, 0.20)} |",
            f"| Language Detected | `{(m.language_detected or 'unknown').upper()}` | {pct(m.language_confidence)} |",
            f"| Compression Ratio | `{m.compression_ratio:.2f}` | {self._compression_status(m.compression_ratio)} |",
            f"| No-Speech Probability | {pct(m.no_speech_probability)} | {'High' if m.no_speech_probability > 0.5 else 'Low'} |",
            f"| Duration | {self._format_time(m.duration_seconds)} | |",
            f"| Speaking Rate | {m.speaking_rate_wpm:.0f} WPM | |",
            f"| Total Words | {m.total_words} | |",
            f"| Vocabulary Density | {pct(m.vocabulary_density)} | |",
            f"| Pause Count (>0.3s) | {m.pause_count} | |",
            f"| Avg. Pause Duration | {m.avg_pause_duration:.2f}s | |",
        ]
        return lines

    def _render_segments(self, segments: List[Dict[str, Any]]) -> str:
        if not segments:
            return "_No segments._"
        out: List[str] = []
        for seg in segments:
            start = self._format_time(float(seg.get("start", 0.0)))
            end = self._format_time(float(seg.get("end", 0.0)))
            speaker = seg.get("speaker")
            prefix = f"**[{start} → {end}]** "
            if speaker:
                prefix += f"`{speaker}` "
            out.append(prefix + (seg.get("text") or "").strip())
        return "\n\n".join(out)

    def _render_low_confidence(self, words: List[LowConfidenceWord]) -> str:
        if not words:
            return "No low-confidence words detected."
        lines = ["| Word | Timestamp | Confidence |", "|---|---:|---:|"]
        for w in words:
            lines.append(f"| `{w.word}` | {w.start:.2f}s | {w.confidence*100:.1f}% |")
        return "\n".join(lines)

    def _render_speaker_timeline(self, diar: DiarizationResult) -> str:
        lines: List[str] = []
        for t in diar.turns[:200]:
            lines.append(
                f"- **{self._format_time(t.start)} → {self._format_time(t.end)}** `{t.speaker}`"
            )
        if len(diar.turns) > 200:
            lines.append(f"- _... {len(diar.turns) - 200} more turns_")
        return "\n".join(lines)

    def _compression_status(self, ratio: float) -> str:
        if ratio < 1.8:
            return "Safe"
        if ratio < 2.4:
            return "Monitor"
        return "HallucinationRisk"

    def _format_time(self, seconds: float) -> str:
        td = timedelta(seconds=float(seconds or 0.0))
        total_s = int(td.total_seconds())
        ms = int((td.total_seconds() - total_s) * 1000)
        h, rem = divmod(total_s, 3600)
        m, s = divmod(rem, 60)
        return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"

    def _file_hash(self, path: str) -> str:
        try:
            with open(path, "rb") as f:
                return hashlib.sha256(f.read()).hexdigest()[:16]
        except Exception:
            return "N/A"

    def _to_jsonable(self, obj: Any) -> Any:
        if obj is None:
            return None
        if is_dataclass(obj):
            return asdict(obj)
        return obj

